name: DevOps Practice

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Say Hello
      run: echo "Hello DevOps, your first workflow is running!"
